definitions:
  db.Deck:
    properties:
      created_at:
        type: string
      desc:
        type: string
      id:
        type: string
      is_public:
        type: boolean
      name:
        type: string
      pid:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  db.Tag:
    properties:
      cid:
        type: string
      created_at:
        type: string
      id:
        type: string
      key:
        type: string
      updated_at:
        type: string
    type: object
  handler.RegisterParam:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
info:
  contact:
    email: zcharyma@gmail.com
    name: Zchary
    url: https://github.com/zchary-ma
  description: Znki API documentation
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Znki API doc
  version: "0.1"
paths:
  /decks:
    get:
      consumes:
      - application/json
      description: get deck list
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: get deck list
      tags:
      - Deck
  /decks/{id}:
    delete:
      consumes:
      - application/json
      description: delete deck by deck id
      parameters:
      - description: Deck ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: delete deck by deck id
      tags:
      - Deck
  /decks/add:
    post:
      consumes:
      - application/json
      description: create deck
      parameters:
      - description: deck info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/db.Deck'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"success"}'
          schema:
            type: string
      summary: create deck
      tags:
      - Deck
  /login:
    post:
      consumes:
      - application/json
      description: login
      produces:
      - application/json
      responses:
        "201":
          description: '{"code":200,"data":{},"msg":"success"}'
          schema:
            type: string
      summary: login
      tags:
      - User
  /logout:
    post:
      consumes:
      - application/json
      description: logout
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"success"}'
          schema:
            type: string
      summary: logout
      tags:
      - User
  /register:
    post:
      consumes:
      - application/json
      description: user register
      parameters:
      - description: user info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.RegisterParam'
      produces:
      - application/json
      responses:
        "201":
          description: '{"code":200,"data":{},"msg":"success"}'
          schema:
            type: string
      summary: list decks from user
      tags:
      - User
  /tags:
    get:
      consumes:
      - application/json
      description: create tag
      parameters:
      - description: card_id
        in: query
        name: card_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"success"}'
          schema:
            type: string
      summary: create tag
      tags:
      - Tag
  /tags/{id}:
    delete:
      consumes:
      - application/json
      description: remove tag
      parameters:
      - description: Tag ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"success"}'
          schema:
            type: string
      summary: remove tag
      tags:
      - Tag
    put:
      consumes:
      - application/json
      description: edit tag
      parameters:
      - description: tag info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/db.Tag'
      - description: Tag ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"success"}'
          schema:
            type: string
      summary: edit tag
      tags:
      - Tag
  /tags/add:
    post:
      consumes:
      - application/json
      description: create tag
      parameters:
      - description: tag info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/db.Tag'
      produces:
      - application/json
      responses:
        "201":
          description: '{"code":200,"data":{},"msg":"success"}'
          schema:
            type: string
      summary: create tag
      tags:
      - Tag
  /user:
    put:
      consumes:
      - application/json
      description: update user info
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"success"}'
          schema:
            type: string
      summary: update user info
      tags:
      - User
swagger: "2.0"
